//! Takes from `vendor/hf.map.json` only the keys the autosplitter needs, and
//! emits them as constants.
//!
//! The full table has 2952 entries and 75 KiB. Embedding it in the `.wasm`
//! would make no sense. Generating the keys here, rather than copying the
//! strings by hand, keeps one single source of truth: if the table changes,
//! the build follows, and a key that disappears breaks the build instead of
//! producing an autosplitter that finds nothing at run time.
//!
//! No dependencies. Every build crate adds a procedural macro or a script to
//! compile for the host machine, and the reader below is thirty lines long.

use std::{collections::BTreeMap, env, fs, path::Path};

/// (name of the constant, identifier in the Hammerfest source)
const WANTED: &[(&str, &str)] = &[
    ("WORLD", "world"),
    ("MANAGER", "manager"),
    ("CURRENT", "current"),
    ("F_VERSION", "fVersion"),
    ("CURRENT_ID", "currentId"),
    ("PREVIOUS_ID", "_previousId"),
    ("SET_NAME", "setName"),
    ("GAME_CHRONO", "gameChrono"),
    ("CURRENT_DIM", "currentDim"),
    ("FL_GAME_OVER", "fl_gameOver"),
    ("FRAME_TIMER", "frameTimer"),
    ("GAME_TIMER", "gameTimer"),
    ("HALTED_TIMER", "haltedTimer"),
    ("FL_STOP", "fl_stop"),
    ("FL_LOCK", "fl_lock"),
    // The end of the run. `ScriptEngine.codeTrigger` case 4 -- "sortie par
    // l'ascenseur" -- writes it in the frame where the player enters the
    // elevator. No other line of the adventure writes it.
    ("END_MODE_TIMER", "endModeTimer"),
];

/// Identifiers the obfuscator leaves as they are.
///
/// These are names from the standard AS2 API. Renaming them would break the
/// Flash player itself. Their absence from the table is therefore the right
/// answer, not an error -- but their *presence* would be an error, because it
/// would mean the table changed its convention. Hence the check.
const WANTED_PLAIN: &[(&str, &str)] = &[("DURATION", "duration")];

/// The world names. They are obfuscated too, because they look like
/// identifiers. We use them to check that a `GameMechanics` really is a world.
const WORLDS: &[&str] = &[
    "xml_adventure",
    "xml_deepnight",
    "xml_hiko",
    "xml_ayame",
    "xml_hk",
];

fn main() {
    let map_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("vendor/hf.map.json");
    println!("cargo:rerun-if-changed={}", map_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let raw = fs::read_to_string(&map_path).expect("cannot read vendor/hf.map.json");
    let map = parse_flat_object(&raw);

    let lookup = |clear: &str| -> &str {
        map.get(clear)
            .unwrap_or_else(|| panic!("{clear:?} is missing from vendor/hf.map.json"))
            .as_str()
    };

    // Plain comments and not `//!`: this file is included inside a module
    // that is already open, where an inner doc comment has no place.
    let mut out = String::from(
        "// Generated by build.rs from vendor/hf.map.json. Do not edit.\n\
         //\n\
         // Property names as they appear in the obfuscated SWF.\n\n",
    );
    for (konst, clear) in WANTED {
        out.push_str(&format!(
            "/// `{clear}`\npub const {konst}: &str = {:?};\n",
            lookup(clear)
        ));
    }
    for (konst, clear) in WANTED_PLAIN {
        assert!(
            !map.contains_key(*clear),
            "{clear:?} is now renamed in hf.map.json: move it to WANTED"
        );
        out.push_str(&format!(
            "/// `{clear}`, which the obfuscator does not rename.\n\
             pub const {konst}: &str = {clear:?};\n"
        ));
    }
    out.push_str(
        "\n/// The worlds, obfuscated name then clear name. The first one is\n\
         /// the main world, the one of the adventure.\n\
         pub const WORLDS: &[(&str, &str)] = &[\n",
    );
    for clear in WORLDS {
        out.push_str(&format!("    ({:?}, {clear:?}),\n", lookup(clear)));
    }
    out.push_str("];\n");

    let dst = Path::new(&env::var("OUT_DIR").unwrap()).join("keys.rs");
    fs::write(dst, out).expect("cannot write keys.rs");
}

/// Reads a flat JSON object `{"key": "value", ...}`.
///
/// The table holds only ASCII strings with no escape sequence. That is
/// checked, not assumed: any escape sequence fails the build instead of
/// producing a key that is silently wrong.
fn parse_flat_object(src: &str) -> BTreeMap<String, String> {
    let mut map = BTreeMap::new();
    let mut chars = src.char_indices().peekable();
    let mut pending: Option<String> = None;

    while let Some((i, c)) = chars.next() {
        match c {
            '"' => {
                let start = i + 1;
                let mut end = None;
                for (j, c) in chars.by_ref() {
                    if c == '\\' {
                        panic!(
                            "JSON escape at offset {j}: this minimal reader does \
                             not handle them, it must be extended"
                        );
                    }
                    if c == '"' {
                        end = Some(j);
                        break;
                    }
                }
                let s = src[start..end.expect("unterminated JSON string")].to_string();
                match pending.take() {
                    None => pending = Some(s),
                    Some(key) => {
                        map.insert(key, s);
                    }
                }
            }
            '{' | '}' | ':' | ',' => {}
            c if c.is_whitespace() => {}
            c => panic!("unexpected character {c:?} at offset {i}"),
        }
    }
    assert!(pending.is_none(), "key with no value at the end of the file");
    assert!(!map.is_empty(), "vendor/hf.map.json is empty");
    map
}
